### ISSUE TITLE
Store skins on a stateful partition

### ISSUE THREAD

**Issue by andrewhowdencom** [bitnami/bitnami-docker-mediawiki#47]
Currently, extensions are installed on a stateful partition and are thus preserved between reboots. It'd be good to see skins similarly stored -- that'd let me drop in a custom design.

**Comment by dgonzalezruiz** [comment]
Hi @andrewhowdencom ,

I have released a new revision fixing this. The `skins` folder is now persisted. This should solve your issue.

Let us know if you find any issue while trying it out! :) Thanks a lot for your feedback.

**Comment by andrewhowdencom** [comment]
Hola, 

Thanks! However, the doesn't seem to be a clean upgrade path between the two versions: 
```
Welcome to the Bitnami mediawiki container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mediawiki
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mediawiki/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
nami    INFO  apache successfully initialized
nami    INFO  Initializing mediawiki
mysqlCo INFO  Trying to connect to MySQL server
mysqlCo INFO  Found MySQL server listening at wiki-mariadb:3306
mysqlCo INFO  MySQL server listening and working at wiki-mariadb:3306
Error executing 'postInstallation': PHP Fatal error:  Uncaught exception 'Exception' with message '/opt/bitnami/mediawiki/skins/CologneBlue/skin.json does not exist!' in /opt/bitnami/mediawiki/includes/registration/ExtensionRegistry.php:107
Stack trace:
#0 /opt/bitnami/mediawiki/includes/GlobalFunctions.php(153): ExtensionRegistry->queue('/opt/bitnami/me...')
#1 /bitnami/mediawiki/LocalSettings.php(159): wfLoadSkin('CologneBlue')
#2 /opt/bitnami/mediawiki/maintenance/doMaintenance.php(84): require('/bitnami/mediaw...')
#3 /opt/bitnami/mediawiki/maintenance/update.php(217): require_once('/opt/bitnami/me...')
#4 {main}
  thrown in /opt/bitnami/mediawiki/includes/registration/ExtensionRegistry.php on line 107
```

Is this within scope of the container, or should I perform a manual migration?

**Comment by dgonzalezruiz** [comment]
Hi @andrewhowdencom ,

I just released a new revision of the image fixing this issue. As you said, it wasn't in the scope of the image until now, but now it is in all of our images! 

Thanks a ton for your feedback.

**Comment by sameersbn** [comment]
closing.. please re-open if the issue persists.
