### ISSUE TITLE
Issue with external database

### ISSUE THREAD

**Issue by sozercan** [bitnami/bitnami-docker-mediawiki#64]
**Description**

Getting this issue below when trying to use an external database (MySql on Azure) when deploying on Kubernetes. Seems like it is trying to look for the `interwiki` table but didn't create for some reason. It does create other tables.

Is this a permissions issue?

```
nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing mediawiki
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at a7a1567f-bcd4-4f1f-9728-56ddad2e1f22.mysql.database.azure.com:3306
mysql-c INFO  MySQL server listening and working at a7a1567f-bcd4-4f1f-9728-56ddad2e1f22.mysql.database.azure.com:3306
Error executing 'postInstallation': /usr/bin/locale: Cannot set LC_CTYPE to default locale: No such file or directory
[91596cde6e4f7f92ad53db89] [no req]   Wikimedia\Rdbms\DBQueryError from line 1075 of /opt/bitnami/mediawiki/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading?
Query: SELECT  *  FROM `interwiki`     LIMIT 1
Function: DatabaseInstaller::populateInterwikiTable
Error: 1146 Table 'vfpb2dki3j.interwiki' doesn't exist (a7a1567f-bcd4-4f1f-9728-56ddad2e1f22.mysql.database.azure.com)

Backtrace:
#0 /opt/bitnami/mediawiki/includes/libs/rdbms/database/Database.php(933): Wikimedia\Rdbms\Database->reportQueryError(string, integer, string, string, boolean)
#1 /opt/bitnami/mediawiki/includes/libs/rdbms/database/Database.php(1269): Wikimedia\Rdbms\Database->query(string, string)
#2 /opt/bitnami/mediawiki/includes/libs/rdbms/database/Database.php(1337): Wikimedia\Rdbms\Database->select(string, string, array, string, array, array)
#3 /opt/bitnami/mediawiki/includes/installer/DatabaseInstaller.php(700): Wikimedia\Rdbms\Database->selectRow(string, string, array, string)
#4 /opt/bitnami/mediawiki/includes/installer/Installer.php(1519): DatabaseInstaller->populateInterwikiTable(MysqlInstaller)
#5 /opt/bitnami/mediawiki/includes/installer/CliInstaller.php(135): Installer->performInstallation(array, array)
#6 /opt/bitnami/mediawiki/maintenance/install.php(142): CliInstaller->execute()
#7 /opt/bitnami/mediawiki/maintenance/doMaintenance.php(111): CommandLineInstaller->execute()
#8 /opt/bitnami/mediawiki/maintenance/install.php(156): require_once(string)
#9 {main}
```

**Comment by javsalgar** [comment]
Hi,

Have you tried using these env vars from https://github.com/bitnami/bitnami-docker-mediawiki:

- MYSQL_CLIENT_CREATE_DATABASE_NAME: New database to be created by the mysql client module. No defaults.
- MYSQL_CLIENT_CREATE_DATABASE_USER: New database user to be created by the mysql client module. No defaults.
- MYSQL_CLIENT_CREATE_DATABASE_PASSWORD: Database password for the MYSQL_CLIENT_CREATE_DATABASE_USER user. No defaults.

**Comment by sozercan** [comment]
@javsalgar added those vars and `MARIADB_ROOT_USER` and `MARIADB_ROOT_PASSWORD` and getting same error.

```
mysql-c INFO  MySQL server listening and working at c2a0bd8d-0eb4-4cab-9289-2acbbe42db28.mysql.database.azure.com:3306
Error executing 'postInstallation': /usr/bin/locale: Cannot set LC_CTYPE to default locale: No such file or directory
[e221cf1268929d94059d06a0] [no req]   Wikimedia\Rdbms\DBQueryError from line 1075 of /opt/bitnami/mediawiki/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading?
Query: SELECT  *  FROM `interwiki`     LIMIT 1
Function: DatabaseInstaller::populateInterwikiTable
Error: 1146 Table 'ylskx9ub8a.interwiki' doesn't exist (c2a0bd8d-0eb4-4cab-9289-2acbbe42db28.mysql.database.azure.com)
```

**Comment by sameersbn** [comment]
@sozercan the issue is probably related to permissions of the database user on the mediawiki database. Can you retry after granting the database user ALL permissions to the mediawiki database?

**Comment by sameersbn** [comment]
FWIW, I tried the following experiment to simulate the environment:

1. Start a Mariadb container

```bash
$ docker network create mediawiki-tier
$ docker volume create --name mariadb_data
$ docker run -it --rm --name mariadb --net mediawiki-tier --volume mariadb_data:/bitnami \
     --env MARIADB_ROOT_PASSWORD=secretpassword bitnami/mariadb:latest
```

2. Create a database and user for mediawiki app

```bash
$ docker exec -it mariadb mysql -uroot -psecretpassword
```

```sql
CREATE DATABASE IF NOT EXISTS `wikidb` DEFAULT CHARACTER SET `utf8` COLLATE `utf8_unicode_ci`;
GRANT ALL PRIVILEGES ON `wikidb`.* TO 'mediawiki' IDENTIFIED BY 'password';
```

3. Launch the Mediawiki app

```bash
$ docker volume create --name mediawiki_data
$ docker run -it --rm  --name mediawiki -p 80:80 --net mediawiki-tier \
     -e MEDIAWIKI_DATABASE_USER=mediawiki \
     -e MEDIAWIKI_DATABASE_PASSWORD=password \
     -e MEDIAWIKI_DATABASE_NAME=wikidb  \
     --volume mediawiki_data:/bitnami bitnami/mediawiki:latest
```
